/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fastrequest.view;

import Excecoes.ValidarCpfException;
import Excecoes.ValidarEmailException;
import Excecoes.ValidarTelefoneException;
import br.com.fastrequest.controller.ClienteController;
import br.com.fastrequest.model.Cliente;
import br.com.fastrequest.model.ValidaCpf;
import br.com.fastrequest.model.ValidaEmail;
import br.com.fastrequest.model.ValidaTelefone;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * 
 * @author Yeltsin
 */
public class AlterarCadastroCliente extends javax.swing.JFrame {

	/**
	 * Creates new form CadastroCliente
	 */
	public AlterarCadastroCliente() {
		initComponents();
	}

	private List<Cliente> clienteList = new ClienteController().listaClientes();
	private int registro = 0;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCliente = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JLabel();
        telefoneCliente = new javax.swing.JLabel();
        emailCliente = new javax.swing.JLabel();
        textNomeCliente = new javax.swing.JTextField();
        textCpfCliente = new javax.swing.JTextField();
        textTelefoneCliente = new javax.swing.JTextField();
        textEmailCliente = new javax.swing.JTextField();
        textNomeCpfEditar = new javax.swing.JTextField();
        txtClienteEditar = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fast Request");

        nomeCliente.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        nomeCliente.setText("Nome");

        cpfCliente.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        cpfCliente.setText("CPF");

        telefoneCliente.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        telefoneCliente.setText("Telefone");

        emailCliente.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        emailCliente.setText("Email");

        textNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeClienteActionPerformed(evt);
            }
        });

        textCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfClienteActionPerformed(evt);
            }
        });

        textTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTelefoneClienteActionPerformed(evt);
            }
        });

        txtClienteEditar.setText("Editar");
        txtClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteEditarActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Digite o CPF do cliente");

        btnTo.setText("Sair");
        btnTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(nomeCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cpfCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(telefoneCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(textTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNomeCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClienteEditar))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailCliente)
                                .addGap(41, 41, 41)
                                .addComponent(textEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTo)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteEditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCliente)
                    .addComponent(textNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCliente)
                    .addComponent(textCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneCliente)
                    .addComponent(textTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailCliente)
                    .addComponent(textEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnTo))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnToActionPerformed

	private void textNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textNomeClienteActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textNomeClienteActionPerformed

	private void textCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textCpfClienteActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textCpfClienteActionPerformed

	private void textTelefoneClienteActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textTelefoneClienteActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textTelefoneClienteActionPerformed

	private void txtClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtClienteEditarActionPerformed

		ClienteController pc = new ClienteController();
		try {
			Cliente p = pc.buscaContatoPorCPF(textNomeCpfEditar.getText());
			textNomeCliente.setText(p.getNome());
			textCpfCliente.setText(p.getCpf());
			textEmailCliente.setText(p.getEmail());
			textTelefoneCliente.setText(p.getTelefone());
			JOptionPane.showMessageDialog(null, "Cadastro encontrado com sucesso! ");

		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Conexao com banco falhou.");
			Logger.getLogger(TelaProduto2.class.getName()).log(Level.SEVERE,
					null, ex);
		} catch (NullPointerException e1) {
			JOptionPane.showMessageDialog(null, "Cadastro nao encontrado.");

		}// TODO add your handling code here:
	}// GEN-LAST:event_txtClienteEditarActionPerformed

	private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		
		try {
			
			ClienteController pc = new ClienteController();
			Cliente p = pc.buscaContatoPorCPF(textCpfCliente.getText());
	
			
                        ValidaCpf cpf = new ValidaCpf();
                        ValidaTelefone telefone = new ValidaTelefone();
                        ValidaEmail email = null;
                       
                        if (cpf.validarCpf(textCpfCliente.getText()) == false) {
                            throw new ValidarCpfException();
                        }
            
                        if (email.validaEmail(textEmailCliente.getText()) == false) {
                            throw new ValidarEmailException();
                        }
            
                        if(telefone.validaTelefone(textTelefoneCliente.getText()) == false) {
                            throw new ValidarTelefoneException();
                        }
                        
			int id = clienteList.get(registro).getId();
			
			pc.alterar(id, textNomeCliente.getText(), textCpfCliente.getText(),
			 textEmailCliente.getText(),textTelefoneCliente.getText());
			
                        JOptionPane.showMessageDialog(this, "Cadastro alterado com sucesso!");
			textNomeCliente.setText("");
			textCpfCliente.setText("");
			textTelefoneCliente.setText("");
			textEmailCliente.setText("");
			textNomeCpfEditar.setText("");

		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(nomeCliente,
					"Conexao com banco falhou.");

		} catch (ParseException ex) {
			JOptionPane.showMessageDialog(this,
					"Teste.");
		}
		catch (IndexOutOfBoundsException ex) {
			JOptionPane.showMessageDialog(this,
					"Cliente nao encontrado.");
           
                }catch (ValidarTelefoneException ex) {
                        JOptionPane.showMessageDialog(this, "Telefone invalido. \n Digite o DDD e o Numero (9 ou 8 digitos).");
                  
                } catch (ValidarCpfException ex) {
                        JOptionPane.showMessageDialog(this, "CPF invalido.");
            
                } catch (IllegalArgumentException e1){
                        JOptionPane.showMessageDialog(this, e1.getMessage());
       
                } catch (ValidarEmailException ex) {
                        JOptionPane.showMessageDialog(this, "Email invalido.");
            
                }catch (NullPointerException e1){
                        JOptionPane.showMessageDialog(this, "Favor preencher todos os campos.");
                }
	
		
	}// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JToggleButton btnTo;
    private javax.swing.JLabel cpfCliente;
    private javax.swing.JLabel emailCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeCliente;
    private javax.swing.JLabel telefoneCliente;
    private javax.swing.JTextField textCpfCliente;
    private javax.swing.JTextField textEmailCliente;
    private javax.swing.JTextField textNomeCliente;
    private javax.swing.JTextField textNomeCpfEditar;
    private javax.swing.JTextField textTelefoneCliente;
    private javax.swing.JButton txtClienteEditar;
    // End of variables declaration//GEN-END:variables
}
