/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fastrequest.view;

/**
 *
 * @author Antonio
 */
public class TelaAcompanhamentoFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAcompanhamentoFuncionario
     */
    public TelaAcompanhamentoFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        PedidosAndamento = new javax.swing.JPanel();
        btnConcluido = new javax.swing.JButton();
        NumeroPedido1 = new javax.swing.JLabel();
        txtNumeroPedido1 = new javax.swing.JTextField();
        PedidosProntos = new javax.swing.JPanel();
        btnPago = new javax.swing.JButton();
        NumeroPedido2 = new javax.swing.JLabel();
        txtNumeroPedido2 = new javax.swing.JTextField();
        PedidosPago = new javax.swing.JPanel();
        btnNotaFiscal = new javax.swing.JButton();
        btnRelatorioDia = new javax.swing.JButton();
        btnVoltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/fastrequest/imagens/logo2.jpg"))); // NOI18N

        PedidosAndamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "PEDIDOS EM ANDAMENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnConcluido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConcluido.setText("CONCLUIDO");
        btnConcluido.setPreferredSize(new java.awt.Dimension(50, 25));
        btnConcluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluidoActionPerformed(evt);
            }
        });

        NumeroPedido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumeroPedido1.setText("Numero do Pedido");

        txtNumeroPedido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PedidosAndamentoLayout = new javax.swing.GroupLayout(PedidosAndamento);
        PedidosAndamento.setLayout(PedidosAndamentoLayout);
        PedidosAndamentoLayout.setHorizontalGroup(
            PedidosAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosAndamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidosAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidosAndamentoLayout.createSequentialGroup()
                        .addComponent(NumeroPedido1)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(PedidosAndamentoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNumeroPedido1)))
                .addGap(18, 18, 18)
                .addComponent(btnConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PedidosAndamentoLayout.setVerticalGroup(
            PedidosAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosAndamentoLayout.createSequentialGroup()
                .addContainerGap(463, Short.MAX_VALUE)
                .addGroup(PedidosAndamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosAndamentoLayout.createSequentialGroup()
                        .addComponent(NumeroPedido1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosAndamentoLayout.createSequentialGroup()
                        .addComponent(btnConcluido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        PedidosProntos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "PEDIDOS PRONTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPago.setText("PAGO");
        btnPago.setPreferredSize(new java.awt.Dimension(75, 25));
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });

        NumeroPedido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumeroPedido2.setText("Numero do Pedido");

        txtNumeroPedido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout PedidosProntosLayout = new javax.swing.GroupLayout(PedidosProntos);
        PedidosProntos.setLayout(PedidosProntosLayout);
        PedidosProntosLayout.setHorizontalGroup(
            PedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosProntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PedidosProntosLayout.createSequentialGroup()
                        .addComponent(NumeroPedido2)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(PedidosProntosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNumeroPedido2)))
                .addGap(18, 18, 18)
                .addComponent(btnPago, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PedidosProntosLayout.setVerticalGroup(
            PedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosProntosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PedidosProntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PedidosProntosLayout.createSequentialGroup()
                        .addComponent(NumeroPedido2)
                        .addGap(7, 7, 7)
                        .addComponent(txtNumeroPedido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PedidosPago.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "PEDIDOS PAGOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnNotaFiscal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNotaFiscal.setText("Nota Fiscal");
        btnNotaFiscal.setPreferredSize(new java.awt.Dimension(75, 25));
        btnNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaFiscalActionPerformed(evt);
            }
        });

        btnRelatorioDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRelatorioDia.setText("Relatorio do Dia");
        btnRelatorioDia.setPreferredSize(new java.awt.Dimension(75, 25));
        btnRelatorioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioDiaActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PedidosPagoLayout = new javax.swing.GroupLayout(PedidosPago);
        PedidosPago.setLayout(PedidosPagoLayout);
        PedidosPagoLayout.setHorizontalGroup(
            PedidosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosPagoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PedidosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PedidosPagoLayout.createSequentialGroup()
                        .addComponent(btnNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnRelatorioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PedidosPagoLayout.setVerticalGroup(
            PedidosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PedidosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotaFiscal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PedidosAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PedidosProntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(PedidosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PedidosAndamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PedidosProntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PedidosPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConcluidoActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagoActionPerformed

    private void btnNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaFiscalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotaFiscalActionPerformed

    private void btnRelatorioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatorioDiaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaProduto2 tela = new TelaProduto2();
        tela.setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NumeroPedido1;
    private javax.swing.JLabel NumeroPedido2;
    private javax.swing.JPanel PedidosAndamento;
    private javax.swing.JPanel PedidosPago;
    private javax.swing.JPanel PedidosProntos;
    private javax.swing.JButton btnConcluido;
    private javax.swing.JButton btnNotaFiscal;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnRelatorioDia;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JTextField txtNumeroPedido1;
    private javax.swing.JTextField txtNumeroPedido2;
    // End of variables declaration//GEN-END:variables
}
